version: "4.25.1"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: server-development
    # volumes:
    #   - ./:/usr/src/development/server
    #   - /usr/src/development/server/node_modules
    ports:
      - 4000:4000
    command: npm run start:dev

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: client-development
    # volumes:
    #   - ./:/usr/src/development/client
    #   - /usr/src/development/client/node_modules
    ports:
      - 5173:5173
    command: npm run dev -- --host 0.0.0.0